# Generated by Django 3.2.16 on 2023-10-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20231021_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postee',
            new_name='post',
        ),
    ]
